page 53150 "JMC Payroll Import Setup"
{
    Caption = 'Payroll Import Setup', Comment = 'ESP="Configuración importación nóminas"';
    PageType = Card;
    SourceTable = "JMC Payroll Import Setup";
    UsageCategory = Administration;
    ApplicationArea = All;
    InsertAllowed = false;
    DeleteAllowed = false;

    layout
    {
        area(Content)
        {
            group(Journal)
            {
                Caption = 'Journal', Comment = 'ESP="Diario"';

                field(JournalTemplateName; Rec."JMC Journal Template Name") { }
                field(JournalBatchName; Rec."JMC Journal Batch Name") { }
                field(DocumentNoSeries; Rec."JMC Document No. Series") { }
            }
            group(Checks)
            {
                Caption = 'Checks', Comment = 'ESP="Comprobaciones"';

                field(BalanceTolerance; Rec."JMC Balance Tolerance") { }
            }
        }
    }

    actions
    {
        area(Navigation)
        {
            action(ConceptSetup)
            {
                Caption = 'Concept Accounts', Comment = 'ESP="Cuentas por concepto"';
                ToolTip = 'Set up the G/L account proposed for each payroll concept.', Comment = 'ESP="Configura la cuenta contable que se propone para cada concepto de nómina."';
                Image = ChartOfAccounts;
                RunObject = page "JMC Payroll Concept Setup";
            }
            action(ColumnMapping)
            {
                Caption = 'Column Mapping', Comment = 'ESP="Mapeo de columnas"';
                ToolTip = 'Set up the concept generated by each column of the Excel file.', Comment = 'ESP="Configura el concepto que genera cada columna del Excel."';
                Image = MapAccounts;
                RunObject = page "JMC Payroll Column Mapping";
            }
            action(GarnishmentAccounts)
            {
                Caption = 'Garnishment Accounts', Comment = 'ESP="Cuentas por organismo embargante"';
                ToolTip = 'Set up the G/L account proposed for each garnishment authority.', Comment = 'ESP="Configura la cuenta contable que se propone para cada organismo embargante."';
                Image = Accounts;
                RunObject = page "JMC Garnishment Account Setup";
            }
        }
        area(Processing)
        {
            action(InitializeDefaults)
            {
                Caption = 'Initialize Defaults', Comment = 'ESP="Inicializar valores por defecto"';
                ToolTip = 'Create the missing concepts, authorities and column mappings with their default values. Existing records are not changed.', Comment = 'ESP="Crea los conceptos, organismos y mapeos de columnas que falten con sus valores por defecto. No modifica los registros existentes."';
                Image = Setup;

                trigger OnAction()
                var
                    jmcPayrollImportMgt: Codeunit "JMC Payroll Import Mgt.";
                begin
                    jmcPayrollImportMgt.InitializeDefaults();
                end;
            }
        }
        area(Promoted)
        {
            actionref(ConceptSetup_Promoted; ConceptSetup) { }
            actionref(ColumnMapping_Promoted; ColumnMapping) { }
            actionref(GarnishmentAccounts_Promoted; GarnishmentAccounts) { }
            actionref(InitializeDefaults_Promoted; InitializeDefaults) { }
        }
    }

    trigger OnOpenPage()
    begin
        Rec.Reset();
        Rec.GetSetup();
    end;
}
